name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Allure report V2
        uses: QuintilianoNery/action-allure-report-V2@0.2.0

