name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Gradle build
        run: ./gradlew build
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

