name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  test:
    name: Run tests and generate Allure report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
      - name: Build with Gradle
        run: ./gradlew clean build test
      - name: Generate Allure report
        uses: allure-framework/allure2-github-action@v2
        with:
          version: '2.17.3'
          allure-command: ${{ github.workspace }}/gradlew
          allure-command-options: 'test'
          results-directory: ${{ github.workspace }}/build/allure-results
          report-directory: ${{ github.workspace }}/build/allure-report
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/allure-report