name: Run tests and generate Allure report
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Run tests with Gradle
        run: ./gradlew test
      - name: Publish Allure results
        uses: allure-framework/allure-github-action@v2.2.0
        with:
          results_dir: build/allure-results
          report_dir: build/reports/build/allure-report
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}