name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/setup-gradle@v1
        with:
          gradle-version: '6.8'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build