name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean test