name: Java CI with Gradle

on:
  push:
    branches: [ action ]
  pull_request:
    branches: [ action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Clean Gradle
        run: ./gradlew clean
      - name: Build with Gradle and run tests
        run: ./gradlew clean test
        continue-on-error: true
      - name: Generate Allure Report
        run: ./gradlew allureReport
      - name: Generate Allure Report
        uses: allure-framework/allure-github-action@v2.0.5
        with:
          results_dir: build/allure-results
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: build/allure-report

#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Allure Report action from marketplace
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: target/allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history

